## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

## Import Data

In [3]:
df_smoteen= pd.read_csv('Data/data_smoteen.csv')  

In [176]:
df_smoteen.shape

(112302, 31)

In [177]:
df_smoteen

Agency Type  Distribution Channel  Duration   Net Sales  \
0                 1                     0       186  -29.000000   
1                 1                     0       186  -29.000000   
2                 1                     1        65  -49.500000   
3                 1                     1        60  -39.600000   
4                 1                     1        79  -19.800000   
...             ...                   ...       ...         ...   
112297            0                     1       365  216.000000   
112298            0                     0        16   30.489583   
112299            1                     1        51   79.200000   
112300            1                     1        57   63.251113   
112301            0                     1       364  216.000000   

        Commision (in value)  Age  Agency_CWT  Agency_EPX  Agency_OTH  \
0                   9.570000   81           0           0           1   
1                   9.570000   71           0           0           1   
2                  29.700000   32           1           0           0   
3                  23.760000   32           1           0           0   
4                  11.880000   41           1           0           0   
...                      ...  ...         ...         ...         ...   
112297             54.000000   37           0           0           0   
112298             10.203453   57           0           0           0   
112299             47.520000   47           1           0           0   
112300              0.000000   36           0           1           0   
112301             54.000000   30           0           0           0   

        Product Name_2 way Comprehensive Plan  ...  Destination_MALAYSIA  \
0                                           0  ...                     1   
1                                           0  ...                     1   
2                                           0  ...                     0   
3                                           0  ...                     0   
4                                           0  ...                     0   
...                                       ...  ...                   ...   
112297                                      0  ...                     0   
112298                                      0  ...                     0   
112299                                      0  ...                     0   
112300                                      0  ...                     0   
112301                                      0  ...                     0   

        Destination_OTHER  Destination_PHILIPPINES  Destination_SINGAPORE  \
0                       0                        0                      0   
1                       0                        0                      0   
2                       0                        0                      0   
3                       0                        0                      0   
4                       1                        0                      0   
...                   ...                      ...                    ...   
112297                  0                        0                      1   
112298                  0                        0                      0   
112299                  1                        0                      0   
112300                  0                        0                      0   
112301                  0                        0                      1   

        Destination_TAIWAN, PROVINCE OF CHINA  Destination_THAILAND  \
0                                           0                     0   
1                                           0                     0   
2                                           0                     0   
3                                           0                     0   
4                                           0                     0   
...                                       ...                 

In [178]:
ee = df_smoteen.columns

## Enter Input Data

In [243]:
df_smoteen['Agency Type'].unique()

array([1, 0], dtype=int64)

In [244]:
a = input()
if a == 'Travel Agency':
    i1 = 1
else:
    i1 = 0
print(i1)

d
0


In [245]:
a = input()
if a == 'Online':
    i2 = 1
else:
    i2 = 0
print(i2)

Online
1


In [246]:
i3 = int(input())

51


In [247]:
i4 = float(input())

60.9209776109215


In [248]:
i5 = float(input())

15.2315600850316


In [249]:
i6 = int(input())

34


In [250]:
agency = input()
i7, i8, i9 = 0,0,0

if agency == 'CWT':
    i7 = 1
elif agency == 'EPX':
    i8 = 1
elif agency == 'OTH':
    i9 = 1

e


In [251]:
ProductName = input()
i10, i11, i12, i13, i14, i15= 0,0,0,0,0,0

if ProductName == '2 way Comprehensive Plan':
    i10 = 1
elif ProductName == 'Basic Plan':
    i11 = 1
elif ProductName == 'Bronze Plan':
    i12 = 1
elif ProductName == 'Cancellation Plan':
    i13 = 1
elif ProductName == 'Other':
    i14 = 1
elif ProductName == 'Rental Vehicle Excess Insurance':
    i15 = 1

E


In [253]:
Destination = input()
i16, i17, i18, i19, i20, i21, i22, i23, i24, i25, i26, i27, i28, i29, i30= 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

if Destination == 'CHINA':
    i16 = 1
elif Destination == 'HONG KONG':
    i17 = 1
elif Destination == 'INDIA':
    i18 = 1
elif Destination == 'INDONESIA':
    i19 = 1
elif Destination == 'JAPAN':
    i20 = 1
elif Destination == 'KOREA, REPUBLIC OF':
    i21 = 1
elif Destination == 'MALAYSIA':
    i22 = 1
elif Destination == 'OTHER':
    i23 = 1
elif Destination == 'PHILIPPINES':
    i24 = 1
elif Destination == 'SINGAPORE':
    i25 = 1
if Destination == 'TAIWAN, PROVINCE OF CHINA':
    i26 = 1
elif Destination == 'THAILAND':
    i27 = 1
elif Destination == 'UNITED KINGDOM':
    i28 = 1
elif Destination == 'UNITED STATES':
    i29 = 1
elif Destination == 'VIET NAM':
    i30 = 1

SINGAPORE


In [254]:
print(i1,i2,i3,i4,i5,i6,i7,i8,i9,i10, i11, i12, i13, i14, i15, i16, i17, i18, i19, i20, i21, i22, i23, i24, i25, i26, i27, i28, i29, i30)

0 1 51 60.9209776109215 15.2315600850316 34 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0


In [255]:
X = df_smoteen.iloc[:, :-1]
y = df_smoteen.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

#Feature Scaling
sc = StandardScaler()
X_train.loc[:,:] = sc.fit_transform(X_train.loc[:,:])
X_test.loc[:,:] = sc.transform(X_test.loc[:,:])

In [256]:
# assign values to lists.  
data = [{'i1':i1,'i2':i2,'i3':i3,'i4':i4,'i5':i5,'i6':i6,'i7':i7,'i8':i8,'i9':i9,'i10':i10, 'i11':i11, 'i12':i12, 'i13':i13, 'i14':i14, 'i15':i15, 'i16':i16, 'i17':i17, 'i18':i18, 'i19':i19, 'i20':i20, 'i21':i21, 'i22':i22, 'i23':i23, 'i24':i24, 'i25':i25, 'i26':i26, 'i27':i27, 'i28':i28, 'i29':i29, 'i30':i30}] 
  
# Creates DataFrame.  
data_new = pd.DataFrame(data)  

In [257]:
list(ee[:-1])

['Agency Type',
 'Distribution Channel',
 'Duration',
 'Net Sales',
 'Commision (in value)',
 'Age',
 'Agency_CWT',
 'Agency_EPX',
 'Agency_OTH',
 'Product Name_2 way Comprehensive Plan',
 'Product Name_Basic Plan',
 'Product Name_Bronze Plan',
 'Product Name_Cancellation Plan',
 'Product Name_Other',
 'Product Name_Rental Vehicle Excess Insurance',
 'Destination_CHINA',
 'Destination_HONG KONG',
 'Destination_INDIA',
 'Destination_INDONESIA',
 'Destination_JAPAN',
 'Destination_KOREA, REPUBLIC OF',
 'Destination_MALAYSIA',
 'Destination_OTHER',
 'Destination_PHILIPPINES',
 'Destination_SINGAPORE',
 'Destination_TAIWAN, PROVINCE OF CHINA',
 'Destination_THAILAND',
 'Destination_UNITED KINGDOM',
 'Destination_UNITED STATES',
 'Destination_VIET NAM']

In [258]:
data_new.columns = list(ee[:-1])

In [259]:
data_new.loc[:,:] = sc.transform(data_new.loc[:,:])

In [260]:
data_new.values

array([[-1.03025835,  0.15386952, -0.21384596, -0.06310529, -0.07762295,
        -0.36315414, -0.32803989, -0.76431548, -0.3561525 , -0.41994906,
        -0.2227343 , -0.30867592, -0.43708795, -0.55678845, -0.32803989,
        -0.21450604, -0.1416618 , -0.13687791, -0.17272509, -0.12681077,
        -0.11192161, -0.23245891, -0.29715939, -0.14382679,  1.2912152 ,
        -0.09081763, -0.22817155, -0.10629465, -0.17385181, -0.11981471]])

## Load Model

In [10]:
rrr= pd.read_csv('Data/classifed.csv')  

In [11]:
rrr[1:2].values

array([[ 0.  ,  1.  , 80.  ,  4.12,  1.16, 48.  ,  0.  ,  0.  ,  1.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,
         0.  ,  0.  ,  0.  ]])

In [12]:
# Loading model to compare the results
model = pickle.load(open('Insurance_Claim_model.pickle','rb'))

In [14]:
model.predict(rrr)

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [9]:
rrr[0:1].values

array([[-1.03025835,  0.15386952, -0.53912642, -0.41563459, -0.32844452,
        -0.80126213, -0.32803989, -0.76431548, -0.3561525 , -0.41994906,
        -0.2227343 , -0.30867592, -0.43708795,  1.79601427, -0.32803989,
        -0.21450604, -0.1416618 , -0.13687791, -0.17272509, -0.12681077,
        -0.11192161, -0.23245891, -0.29715939, -0.14382679,  1.2912152 ,
        -0.09081763, -0.22817155, -0.10629465, -0.17385181, -0.11981471]])